### ISSUE TITLE
Critical error - wordpress

### ISSUE THREAD

**Issue by MarketingSensei** [tagconcierge/tc-wordpress-gtm-consent-mode-banner-free#5]
Hi. I have a problem with activating the plugin after installation, an error appears as in the screenshot.
![image](https://github.com/tagconcierge/tc-wordpress-gtm-consent-mode-banner-free/assets/146414971/d8671b88-3757-4b23-94ea-077b0417a02b)

**Comment by michaloo** [comment]
Hi/Cześć @MarketingSensei,

thanks for reporting it. Can you try installing it from WP plugins directory: https://wordpress.org/plugins/gtm-consent-mode-banner/

It seems GitHub release lacks composer installation and we will fix it.

**Comment by michaloo** [comment]
Hi again. We have added a release with complete ZIP file that should be installable right away without worrying about composer dependencies.
I will close this one for now. Feel free to let me know if issues persist.
